feat:  142 update password auth workflow
MobilityData/mobility-feed-api pull request #186
Opened 2023-11-27 18:58 UTC by qcdyx

**Summary:**
Closes #142 
Finish the UI of Change password screen

**Expected behavior:** 
![image](https://github.com/MobilityData/mobility-feed-api/assets/5789435/4cbe1ba3-7a4d-49b6-8797-930707f43604)

**Testing tips:**

Provide tips, procedures and sample files on how to test the feature.
Testers are invited to follow the tips AND to try anything they deem relevant outside the bounds of the testing tips. 

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `./scripts/api-tests.sh` to make sure you didn't break anything
- [x] Format the title like "feat: [new feature short description]". Title must follow the Conventional Commit Specification(https://www.conventionalcommits.org/en/v1.0.0/).
- [x] Linked all relevant issues
- [x] Include screenshot(s) showing how this pull request works and fixes the issue(s)

2023-11-27 20:30 UTC, davidgamez commented on web-app/src/app/router/Router.tsx
> +      <Route path='change-password' element={<ChangePassword />} />
This should be a protected screen.
```suggestion
<Route element={<ProtectedRoute />}>
      <Route path='change-password' element={<ChangePassword />} />
</Route>
```

2023-11-29 17:32 UTC, emmambd requested changes
2 pieces of feedback on the UI: 

- Change password form should sit in the middle of the page like https://qa.mobilitydatabase.org/sign-up (it might be already, but I can't tell since I can't see the nav items in the screenshot) 
- There should be a toggle view icon option for the New Password and Confirm New Password fields so people can see their new password as they're writing it.

2023-12-07 15:35 UTC, emmambd approved these changes
LGTM from standup!

2023-12-08 16:34 UTC, qcdyx commented
I'll remove my credentials once test is passed.

2023-12-11 19:07 UTC, qcdyx commented
I'm researching on the firebase auth emulator so that I can test Firebase SDK end-to-end workflows.

2023-12-14 21:12 UTC, davidgamez approved these changes
LGTM!

2023-12-14 21:13 UTC, davidgamez commented on web-app/src/app/store/profile-reducer.ts
> +      state.isSignedInWithProvider = false;
👍

2023-12-14 21:14 UTC, merged